# Builds and runs the disk-cache-policy simulation pipeline:
#
#   1. create disk   -> make disk
#   2. disk server   -> make nbd-run      (build + serve the disk over NBD)
#   3. spin up VMs   -> make vms-up       (attach VMs to the running server)
#   4. test on VMs   -> (interactive; ssh/console into a VM and drive it)
#   5. tear down     -> make vms-down
#
# All of it is Linux-only (disk/nbd.cpp needs <endian.h>; kvm/launch.py needs
# qemu-system and /dev/kvm) -- run this on the Linux host/VM that will
# actually host the disk server and the guests.

# Toolchain
CXX := g++

# Build flags (override from CLI if needed, e.g., make CXX=clang++)
CXXFLAGS ?= -std=c++20 -O2 -Wall -Wextra -Wpedantic -pthread
LDFLAGS ?=

# Output directories
BUILD_DIR := build
BIN_DIR := bin

POLICY_SRCS := $(wildcard policies/*.cpp)

.PHONY: dirs clean
dirs:
	@mkdir -p $(BUILD_DIR) $(BIN_DIR) ./logs

clean:
	rm -rf $(BUILD_DIR) $(BIN_DIR)

# ---------------------------------------------------------------------------
# Stage 1: the disk. A backing file that disk/nbd.cpp will serve over the
# NBD wire protocol -- created once as a sparse, zero-filled file of
# DISK_SIZE and left alone after that (delete it yourself to resize/reset).
# `dd` real content into it, or write files to it from inside a guest, once
# VMs can attach.
DISK_IMG ?= disk/data/nbd_disk.img
DISK_SIZE ?= 1G

.PHONY: disk disk-clean
disk: $(DISK_IMG)

$(DISK_IMG):
	@mkdir -p $(dir $(DISK_IMG))
	truncate -s $(DISK_SIZE) $(DISK_IMG)

disk-clean:
	rm -rf $(dir $(DISK_IMG))

# ---------------------------------------------------------------------------
# Stage 2: the disk server. nbd_server (disk/nbd.cpp) serves $(DISK_IMG)
# over the NBD wire protocol so that QEMU VMs can attach it as a plain
# virtio-blk disk -- see disk/nbd.example.yaml for the config schema.
NBD_SRC := disk/nbd.cpp
NBD_BIN := $(BIN_DIR)/nbd_server
NBD_CONFIG ?= disk/nbd.yaml

# One TCP port per client identity the simulator should track separately
# (see disk/nbd.example.yaml) -- space-separated, e.g. NBD_PORTS = 10809 10810.
NBD_PORTS ?= 10809
NBD_CAPACITY ?= 4096
NBD_HIT_LATENCY_NS ?= 30000
NBD_MISS_LATENCY_NS ?= 300000
NBD_WARMUP ?= 0
NBD_EVICT_POLICY ?= lru
NBD_PREFETCH_POLICY ?= none
NBD_LOG ?= ./logs/nbd_results.csv

comma := ,
empty :=
space := $(empty) $(empty)
NBD_PORTS_YAML := $(subst $(space),$(comma)$(space),$(strip $(NBD_PORTS)))

.PHONY: nbd nbd-config nbd-run
nbd: $(NBD_BIN)

$(NBD_BIN): $(NBD_SRC) disk/nbd.hpp disk/sim.hpp $(POLICY_SRCS) | dirs
	$(CXX) $(CXXFLAGS) $(NBD_SRC) $(POLICY_SRCS) -o $@ $(LDFLAGS)

# Regenerated on every invocation (cheap, and keeps it in sync with the
# NBD_* variables) -- unlike the disk image, there's no state here worth
# preserving between runs.
nbd-config:
	@mkdir -p $(dir $(NBD_CONFIG))
	@printf '%s\n' \
		'# Generated by `make nbd-config`; see disk/nbd.example.yaml for the schema.' \
		'source: local' \
		'file: $(DISK_IMG)' \
		'ports: [$(NBD_PORTS_YAML)]' \
		'' \
		'capacity: $(NBD_CAPACITY)' \
		'hit_latency_ns: $(NBD_HIT_LATENCY_NS)' \
		'miss_latency_ns: $(NBD_MISS_LATENCY_NS)' \
		'warmup: $(NBD_WARMUP)' \
		'' \
		'evict_policy: $(NBD_EVICT_POLICY)' \
		'prefetch_policy: $(NBD_PREFETCH_POLICY)' \
		'' \
		'log: $(NBD_LOG)' \
		> $(NBD_CONFIG)
	@echo "wrote $(NBD_CONFIG)"

# Build, provision the backing disk, regenerate the config, and run in the
# foreground. Ctrl-C (or SIGTERM) stops it cleanly and appends one row of
# stats to NBD_LOG. Override any NBD_*/DISK_* variable at invocation, e.g.:
#   make nbd-run NBD_PORTS="10809 10810" DISK_SIZE=4G NBD_EVICT_POLICY=fifo
nbd-run: nbd nbd-config disk
	$(NBD_BIN) $(NBD_CONFIG)

# ---------------------------------------------------------------------------
# Stage 3: the VMs. Wraps kvm/launch.py, which reads a YAML config (see
# kvm/vms.example.yaml) describing one or more QEMU guests and wires each
# guest's disks to nbd_server over the network via `driver=nbd` -- copy
# vms.example.yaml to VMS_CONFIG and point its `nbd.host`/`nbd.port` entries
# at wherever `make nbd-run` above is listening before using this.
VMS_CONFIG ?= kvm/vms.yaml

.PHONY: vms-up vms-down
vms-up:
	python3 kvm/launch.py $(VMS_CONFIG)

vms-down:
	python3 kvm/launch.py $(VMS_CONFIG) --stop
